from enum import StrEnum


class PromptType(StrEnum):
    CODEX_PLAN = "CODEX_PLAN"
    CODEX_IMPLEMENT = "CODEX_IMPLEMENT"
    CLAUDE_REVIEW = "CLAUDE_REVIEW"
    CODEX_FIX = "CODEX_FIX"
    CLAUDE_RECHECK = "CLAUDE_RECHECK"
    ACCEPTANCE_CHECKLIST = "ACCEPTANCE_CHECKLIST"
    README_ARCHIVE = "README_ARCHIVE"
